### ISSUE TITLE
Not working well in macos

### ISSUE THREAD

**Issue by annacruz** [raphaklaus/chupa-cabra#9]
I'm trying to run in a macos and receiving tha message ```env: node\r: No such file or directory```
When run directly in node_modules folder with ```node chupa-cabra.js``` it works fine =)

Ps: I'm also using nvm.

**Comment by raphaklaus** [comment]
Hi Anna! Thank you for the feedback! I will check it ASAP :)

**Comment by annacruz** [comment]
@raphaklaus Solved in version 0.25 =D 😸
